# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe
  - chmod +x conda.exe
  - export CONDA_ALWAYS_YES=1
  - ./conda.exe create -p $HOME/miniconda python=$TRAVIS_PYTHON_VERSION conda conda-build anaconda-client pytest pytest-cov
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --append channels conda-forge
  - conda build conda.recipe --no-test
  - conda install -n test --use-local tranquilizer numpy pandas pillow nbconvert ipython
script:
  - pytest -v --color=yes --cov=tranquilizer tests
after_success:
  - conda install -c conda-forge codecov
  - codecov
