{% set setup_py = load_setup_py_data() %}

package:
  name: 'tranquilizer'
  version: {{ setup_py.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
      - tranquilizer = tranquilizer.__main__:main

requirements:
  run:
   - python >=3.5, <3.8
   - flask
   - werkzeug
   - python-dateutil
   - flask-restplus
  build:
   - python >=3.5, <3.8
   - setuptools

about:
  license: {{ setup_py.get('license') }}
  license_file: LICENSE
  summary: {{ setup_py.get('description') }}

