{% set setup_py = load_setup_py_data() %}

package:
  name: 'tranquilizer'
  version: {{ setup_py.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  entry_points:
      - tranquilizer = tranquilizer.main:run

requirements:
  run:
   - python >=3.5, <3.8
   - flask
   - werkzeug >=0.15
   - python-dateutil
   - flask-restplus
  build:
   - python >=3.5, <3.8
   - setuptools

test:
  source_files:
    - tests
  imports:
    - tranquilizer
  commands:
    - tranquilizer --help
    - py.test -xv tests
  requires:
   - pytest
   - pytest-cov
   - numpy
   - pandas
   - pillow
   - nbconvert

about:
  license: {{ setup_py.get('license') }}
  license_file: LICENSE
  summary: {{ setup_py.get('description') }}

