{% set setup_py = load_setup_py_data() %}

package:
    name: 'tranquilizer'
    version: {{ setup_py.get('version') }}

source:
    path: ../

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - tranquilizer = tranquilizer.__main__:main

requirements:
    run:
        - python
        - flask
        - werkzeug
        - python-dateutil
        - numpy
        - flask-restplus
        - pillow
    build:
        - python
        - setuptools

about:
    license: {{ setup_py.get('license') }}
    license_file: LICENSE
    summary: {{ setup_py.get('description') }}

