name: Build and test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  package:
    name: Build package
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          activate-environment: build-tranq
          environment-file: etc/build-environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Build
        shell: bash -l {0}
        run: |
          conda build conda.recipe --no-test